-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

-- Database: Parking

-- DROP DATABASE "Parking";

CREATE DATABASE "Parking"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE TABLE IF NOT EXISTS public."Cars"
(
    "CarRegNum" character varying(8) NOT NULL,
    "CarOwnerID" integer NOT NULL,
    "CarMakeID" smallint NOT NULL,
    "CarRFID" bigint NOT NULL,
    "CarParkingPlaceID" smallint NOT NULL,
    PRIMARY KEY ("CarRegNum")
);

CREATE TABLE IF NOT EXISTS public."ParkingPlace"
(
    "ParkingPlaceID" smallint NOT NULL,
    "ParkingPlaceType" smallint NOT NULL,
    "IsFree" boolean NOT NULL,
    PRIMARY KEY ("ParkingPlaceID")
);

CREATE TABLE IF NOT EXISTS public."Owners"
(
    "OwnerID" integer NOT NULL,
    "OwnerRFID" bigint NOT NULL,
    "OwnerLastName" character varying(50) NOT NULL,
    "OwnerName" character varying(50) NOT NULL,
    "OwnerMidleName" character varying(50),
    PRIMARY KEY ("OwnerID")
);

CREATE TABLE IF NOT EXISTS public."RFIDs"
(
    "RFIDid" bigint NOT NULL,
    "RFIDtype" smallint NOT NULL,
    "RFIDstatus" boolean NOT NULL,
    PRIMARY KEY ("RFIDid")
);

CREATE TABLE IF NOT EXISTS public."Owners_Cars"
(
    "Owners_OwnerID" integer NOT NULL,
    "Cars_CarRegNum" character varying(8) NOT NULL,
    PRIMARY KEY ("Owners_OwnerID", "Cars_CarRegNum")
);

CREATE TABLE IF NOT EXISTS public."Makes"
(
    "MakeID" smallint NOT NULL,
    "MakeName" character varying(50) NOT NULL,
    PRIMARY KEY ("MakeID")
);

CREATE TABLE IF NOT EXISTS public."ParkigTypes"
(
    "ParkingTypeID" smallint NOT NULL,
    "ParkingTypeName" character varying(20) NOT NULL,
    "ParkingTypeDesc" text,
    PRIMARY KEY ("ParkingTypeID")
);

CREATE TABLE IF NOT EXISTS public."RFIDTypes"
(
    "RFIDTypeID" smallint NOT NULL,
    "RFIDTypeIsPersonal" boolean NOT NULL,
    "RFIDTypeName" character varying(20) NOT NULL,
    PRIMARY KEY ("RFIDTypeID")
);

CREATE TABLE IF NOT EXISTS public."Phones"
(
    "PhoneNum" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    PRIMARY KEY ("PhoneNum", "OwnerId")
);

CREATE TABLE IF NOT EXISTS public."Journal"
(
    "Time" timestamp without time zone NOT NULL,
    "OwnerID" integer NOT NULL,
    "CarID" character varying(8) NOT NULL,
    "InOut" boolean NOT NULL,
    "ParkingPlaceID" smallint NOT NULL,
    PRIMARY KEY ("Time")
);

COMMENT ON COLUMN public."Journal"."InOut"
    IS 'true - In, false- out';

ALTER TABLE public."Cars"
    ADD FOREIGN KEY ("CarRFID")
    REFERENCES public."RFIDs" ("RFIDid")
    NOT VALID;


ALTER TABLE public."Owners"
    ADD FOREIGN KEY ("OwnerRFID")
    REFERENCES public."RFIDs" ("RFIDid")
    NOT VALID;


ALTER TABLE public."Cars"
    ADD FOREIGN KEY ("CarOwnerID")
    REFERENCES public."Owners" ("OwnerID")
    NOT VALID;


ALTER TABLE public."Cars"
    ADD FOREIGN KEY ("CarParkingPlaceID")
    REFERENCES public."ParkingPlace" ("ParkingPlaceID")
    NOT VALID;


ALTER TABLE public."Owners_Cars"
    ADD FOREIGN KEY ("Owners_OwnerID")
    REFERENCES public."Owners" ("OwnerID")
    NOT VALID;


ALTER TABLE public."Owners_Cars"
    ADD FOREIGN KEY ("Cars_CarRegNum")
    REFERENCES public."Cars" ("CarRegNum")
    NOT VALID;


ALTER TABLE public."Cars"
    ADD FOREIGN KEY ("CarMakeID")
    REFERENCES public."Makes" ("MakeID")
    NOT VALID;


ALTER TABLE public."ParkingPlace"
    ADD FOREIGN KEY ("ParkingPlaceType")
    REFERENCES public."ParkigTypes" ("ParkingTypeID")
    NOT VALID;


ALTER TABLE public."RFIDs"
    ADD FOREIGN KEY ("RFIDtype")
    REFERENCES public."RFIDTypes" ("RFIDTypeID")
    NOT VALID;


ALTER TABLE public."Phones"
    ADD FOREIGN KEY ("OwnerId")
    REFERENCES public."Owners" ("OwnerID")
    NOT VALID;


ALTER TABLE public."Journal"
    ADD FOREIGN KEY ("OwnerID")
    REFERENCES public."Owners" ("OwnerID")
    NOT VALID;


ALTER TABLE public."Journal"
    ADD FOREIGN KEY ("CarID")
    REFERENCES public."Cars" ("CarRegNum")
    NOT VALID;


ALTER TABLE public."Journal"
    ADD FOREIGN KEY ("ParkingPlaceID")
    REFERENCES public."ParkingPlace" ("ParkingPlaceID")
    NOT VALID;

END;