-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cars"
(
    "CarRegNum" character varying(8) NOT NULL,
    "CarMakeID" smallint NOT NULL,
    "CarType" smallint,
    PRIMARY KEY ("CarRegNum")
);

CREATE TABLE IF NOT EXISTS public."ParkingPlace"
(
    "ParkingPlaceID" smallint NOT NULL,
    "ParkingPlaceDesc" text,
    PRIMARY KEY ("ParkingPlaceID")
);

CREATE TABLE IF NOT EXISTS public."Persons"
(
    "PersonID" integer NOT NULL,
    "PersonLastName" character varying(50) NOT NULL,
    "PersonName" character varying(50) NOT NULL,
    "PersonMidleName" character varying(50),
    PRIMARY KEY ("PersonID")
);

CREATE TABLE IF NOT EXISTS public."Phones"
(
    "Pnone" bigint NOT NULL,
    "PersonID" integer NOT NULL,
    PRIMARY KEY ("Pnone")
);

CREATE TABLE IF NOT EXISTS public."Makes"
(
    "MakeID" smallint NOT NULL,
    "MakeName" character varying(50) NOT NULL,
    "MakeDescription" text,
    PRIMARY KEY ("MakeID")
);

CREATE TABLE IF NOT EXISTS public."Contract"
(
    "ContractID" smallint NOT NULL,
    "CarNumber" character varying(8) NOT NULL,
    "PersonID" integer NOT NULL,
    "ParkingID" smallint NOT NULL,
    "ContractStart" date NOT NULL,
    "ContractEnd" date NOT NULL,
    PRIMARY KEY ("ContractID")
);

CREATE TABLE IF NOT EXISTS public."CarType"
(
    "CarTypeID" smallint NOT NULL,
    "CarTypeName" character varying NOT NULL,
    PRIMARY KEY ("CarTypeID")
);

ALTER TABLE public."Phones"
    ADD FOREIGN KEY ("PersonID")
    REFERENCES public."Persons" ("PersonID")
    NOT VALID;


ALTER TABLE public."Cars"
    ADD FOREIGN KEY ("CarMakeID")
    REFERENCES public."Makes" ("MakeID")
    NOT VALID;


ALTER TABLE public."Contract"
    ADD FOREIGN KEY ("CarNumber")
    REFERENCES public."Cars" ("CarRegNum")
    NOT VALID;


ALTER TABLE public."Contract"
    ADD FOREIGN KEY ("PersonID")
    REFERENCES public."Persons" ("PersonID")
    NOT VALID;


ALTER TABLE public."Contract"
    ADD FOREIGN KEY ("ParkingID")
    REFERENCES public."ParkingPlace" ("ParkingPlaceID")
    NOT VALID;


ALTER TABLE public."Cars"
    ADD FOREIGN KEY ("CarType")
    REFERENCES public."CarType" ("CarTypeID")
    NOT VALID;

END;